version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-01-25T19-56-04Z
  command: server --console-address ":9001" http://minio{1...4}/data
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "3002:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    image: 'maxzilla2/clowder-fastapi'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_URL: mongodb://mongo:27017
      MINIO_SERVER_URL: nginx:9000
    depends_on:
      - mongo
      - minio1
      - minio2
      - minio3
      - minio4
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=80"

  mongo:
    image: mongo:5.0
    restart: always
    volumes:
      - mongo:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1:/data

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2:/data

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3:/data

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4:/data

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  mongo:
  data1:
  data2:
  data3:
  data4:
