# From https://github.com/ammaraskar/sphinx-action-test/blob/master/.github/workflows/pull_request.yml
name: Sphinx PR

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install libenchant-dev
      run: sudo apt-get install -y libenchant-dev
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"