name: "Pull Request Docs Check"
on:
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install python dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python-dev build-essential gcc
    - name: Build sphinx documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"