# From https://github.com/ammaraskar/sphinx-action-test/blob/master/.github/workflows/pull_request.yml
name: Sphinx PR

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update apt-get
      run: sudo apt-get update
    - name: Install enchant
      run: sudo apt-get install -y enchant
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"